
name: First GitHub Actions # workflow 이름

on: # 언제 workflow가 실행할 지 설정하는 부분
  push: # 코드가 push될 때
    branches:
      - main 
  pull_request: # 풀 리퀘스트가 생성될 때
    branches:
      - main

jobs: # job을 정의하는 부분
  test: # job의 이름은 test
    runs-on: ubuntu-latest # job이 실행되는 환경은 ubuntu 

    steps: # 작업이 실행할 step을 정의하는 부분
      - uses: actions/checkout@v2 # GitHub Action에서 제공하는 checkout action 사용
      
      - name: Set up Python # 해당 step 단계의 이름 정의
        uses: actions/setup-python@v2 # GitHub Action에서 제공하는 setup-python action 사용
        with:
          python-version: '3.x' # python 버전 설정
      
      - name: Run Hello.py # 해당 step 단계의 이름 정의
        run: python Hello.py # Hello.py 파일 실행